"""
phys.py -- Physical property functions for freeze/thaw phase-change modelling.

Translated from the MATLAB sources in ForClaude/ftheta/ (ftheta.m, ftheta_new.m,
ftheta_galushkin.m, ftheta_lunardini.m, ftheta_nicolsky.m). The Hinzman et al.
(1998) formulation, present only as the "hin"/"h" case inside the MATLAB
dispatcher ftheta.m (no standalone .m file existed for it), is included as
one more selectable model.

ftheta() calculates the fluid/ice partition function Theta (and its
derivative dTheta with respect to temperature T) used in the apparent heat
capacity approach to phase change during freezing/thawing.

Calling convention
-------------------
A single public function, ftheta(model, **kwargs), is exposed:

    from phys import ftheta

    out = ftheta("lun", T=T, Tf=0.0, w=0.5)
    Theta, dTheta = out["Theta"], out["dTheta"]

`model` selects the partition function (case-insensitive):
    "lun" / "l"  -> Lunardini (1981)
    "gal" / "g"  -> Galushkin (1997)
    "nic" / "n"  -> Nicolsky, Romanovsky & Tipenko (2007)
    "hin" / "h"  -> Hinzman, Goering & Kane (1998)

`kwargs` must include T (temperature in deg C, array-like or scalar) and,
optionally, the model-specific parameters listed below (all default to the
same values as the original MATLAB code):

    lun: Tf (default 0.0), w (default 0.5)
    gal: Tf (default 0.0)
    nic: Tf (default -0.001), p (default 0.5)   [0.5 <= p <= 0.8, Tf < 0]
    hin: Tb (default [-0.001, -2.0]), p (default 10.0)

The return value is always {"Theta": <ndarray or float>, "dTheta": <ndarray
or float>}, with 0 <= Theta <= 1.

References
----------
Lunardini, V. J.
    Heat Transfer in Cold Climates
    Litton Educational Publishing, 1981
Galushkin, Y.
    Numerical simulation of permafrost evolution as a part of sedimentary
    basin modeling: permafrost in the Pliocene-Holocene climate history of
    the Urengoy field in the West Siberian basin
    Canadian Journal of Earth Sciences, 1997, 34, 935-948
Nicolsky, D. J.; Romanovsky, V. E. & Tipenko, G.
    Estimation of thermal properties of saturated soils using in-situ
    temperature measurements
    The Cryosphere, 2007, 1, 41-58
Hinzman, L.; Goering, D. J. & Kane, D.
    A distributed thermal model for calculating soil temperature profiles
    and depth of thaw in permafrost regions
    Journal of Geophysical Research, 1998, 103, D22, 28975-28991

Original MATLAB: vr, Nov 2010.

Authors: D. Mottaghy (Aachen) & V. Rath (Dublin), with the help of Claude
(Anthropic).

Fluid/ice/rock property functions (props/)
-------------------------------------------
Below ftheta(), this module also collects the water, ice, and rock/matrix
thermophysical property functions translated from props/<site>/*.m (14
site subdirectories; props/arch and props/tmp excluded). Where multiple
sites' MATLAB files for the same property differ only in row/column
reshaping boilerplate, they are consolidated into one function; where the
formulas genuinely differ, each keeps its own name (suffixed with the
alphabetically-first site that uses it, e.g. cpmT_bal, kmT_sg3). See the
comment block above that section for the full accounting, and the
SITE_PROPS dict for a per-site {property_name: function} lookup covering
all 14 sites.

--------------------------------------------------------------------------
Provenance notice: This module was generated by Claude (Anthropic) from the
user's MATLAB sources on 2026-09-14 (ftheta section) and 2026-09-14
(props section). It is AI-generated and should be reviewed (including
against the original MATLAB output for representative test cases) before
use in production.
--------------------------------------------------------------------------
"""

from __future__ import annotations

import numpy as np

__all__ = [
    "ftheta",
    # fluid (water) properties
    "cpfT_fehmn",
    "cpfT_const",
    "rhofT_fehmn",
    "rhofT_const",
    "kfT_phillips",
    "kfT_const",
    # ice properties
    "cpiT_reg",
    "cpiT_fukosako",
    "cpiT_const",
    "rhoiT_reg",
    "rhoiT_const",
    "kiT_reg",
    "kiT_const",
    # rock/matrix properties
    "cpmT_aar",
    "cpmT_bal",
    "cpmT_blz",
    "cpmT_const",
    "cpmT_fmk",
    "cpmT_lax",
    "cpmT_oku",
    "cpmT_sg3",
    "cpmT_syn",
    "kmT_const",
    "kmT_clauser",
    "kmT_olk",
    "kmT_lax",
    "kmT_sg3",
    "rcmT_direct",
    "rcmT_scaled",
    "rcmT_sg3",
    # site registry
    "SITE_PROPS",
]


def _as_float_array(T):
    """Convert T to a float ndarray, remembering whether it was scalar."""
    arr = np.asarray(T, dtype=float)
    is_scalar = arr.ndim == 0
    return np.atleast_1d(arr), is_scalar


def _finalize(Theta, dTheta, is_scalar):
    if is_scalar:
        return {"Theta": float(Theta[0]), "dTheta": float(dTheta[0])}
    return {"Theta": Theta, "dTheta": dTheta}


def _result(x, is_scalar):
    """Return x as a plain float if the input was scalar, else as an ndarray."""
    if is_scalar:
        return float(np.asarray(x).reshape(-1)[0])
    return np.asarray(x, dtype=float)


def _lunardini(T, Tf=0.0, w=0.5):
    """Lunardini (1981) freezing-point-depression partition function.

    Direct translation of ftheta_lunardini.m / the "lun"/"l" branch of
    ftheta.m.
    """
    T, is_scalar = _as_float_array(T)
    Tf = float(Tf)
    w = float(w)

    Theta = np.exp(-(((T - Tf) / w) ** 2))
    frozen_out = T > Tf
    Theta[frozen_out] = 1.0

    a = -2.0 / (w * w)
    dTheta = a * (T - Tf) * Theta
    dTheta[frozen_out] = 0.0

    return _finalize(Theta, dTheta, is_scalar)


def _galushkin(T, Tf=0.0):
    """Galushkin (1997) polynomial partition function.

    Direct translation of ftheta_galushkin.m / the "gal"/"g" branch of
    ftheta.m. The polynomial coefficients are copied verbatim from the
    MATLAB source.
    """
    T, is_scalar = _as_float_array(T)
    Tf = float(Tf)

    a0 = 1.0
    a1 = 0.60152823763179
    a2 = 0.23218232347212
    a3 = 0.04669792788297
    a4 = 0.00535597924776
    a5 = 0.00036415588418
    a6 = 0.00001450956751
    a7 = 0.00000031279149
    a8 = 0.00000000281502

    Theta = (
        a0
        + a1 * T
        + a2 * T**2
        + a3 * T**3
        + a4 * T**4
        + a5 * T**5
        + a6 * T**6
        + a7 * T**7
        + a8 * T**8
    )
    frozen_out = T > Tf
    Theta[frozen_out] = 1.0

    dTheta = (
        a1
        + 2 * a2 * T
        + 3 * a3 * T**2
        + 4 * a4 * T**3
        + 5 * a5 * T**4
        + 6 * a6 * T**5
        + 7 * a7 * T**6
        + 8 * a8 * T**7
    )
    dTheta[frozen_out] = 0.0

    return _finalize(Theta, dTheta, is_scalar)


def _nicolsky(T, Tf=-0.001, p=0.5):
    """Nicolsky, Romanovsky & Tipenko (2007) power-law partition function.

    Follows the "nic"/"n" branch of the ftheta.m dispatcher (including its
    parameter validation), rather than the standalone ftheta_nicolsky.m
    file. The standalone file has an unrelated third argument (`p`) that
    is used in the formula but never given a default, and would raise an
    undefined-variable error in MATLAB if called with fewer than 3
    arguments -- that bug is not reproduced here.
    """
    T, is_scalar = _as_float_array(T)
    Tf = float(Tf)
    p = float(p)

    if not (0.5 <= p <= 0.8 and Tf < 0):
        raise ValueError(
            "ftheta('nic'): incorrect values for parameters p/Tf "
            "(require 0.5 <= p <= 0.8 and Tf < 0)"
        )

    frozen = T < Tf
    Theta = np.ones_like(T)
    Theta[frozen] = np.abs(Tf) ** p * np.abs(T[frozen]) ** (-p)

    dTheta = np.zeros_like(T)
    dTheta[frozen] = (
        np.abs(Tf) ** p
        * (-p)
        * np.abs(T[frozen]) ** (-p - 1)
        * np.sign(T[frozen])
    )

    return _finalize(Theta, dTheta, is_scalar)


def _hinzman(T, Tb=(-0.001, -2.0), p=10.0):
    """Hinzman, Goering & Kane (1998) exponential partition function.

    Direct translation of the "hin"/"h" branch of ftheta.m -- there is no
    standalone ftheta_hinzman.m in the source tree.

    NOTE on dTheta: the original MATLAB branch computes an intermediate
    `fp = f*p` but never actually assigns non-zero values into dTheta
    (dTheta is left as all zeros) -- this looks like an incomplete
    implementation rather than an intentional result. This Python version
    instead returns the analytically correct derivative,
        dTheta/dT = -f * exp(-f*T) / (exp(-f*Tb1) - exp(-f*Tb2))
    within the mushy interval (Tb2 < T < Tb1), and 0 outside it. Flag this
    for review if bit-for-bit MATLAB parity (including the bug) is
    required instead.
    """
    T, is_scalar = _as_float_array(T)
    Tb1, Tb2 = float(Tb[0]), float(Tb[1])
    p = float(p)

    frozen_out = T >= Tb1
    frozen_in = T <= Tb2
    mushy = (T > Tb2) & (T < Tb1)

    f = p / (Tb1 - Tb2)
    denom = np.exp(-f * Tb1) - np.exp(-f * Tb2)

    Theta = np.empty_like(T)
    Theta[frozen_out] = 1.0
    Theta[frozen_in] = 0.0
    Theta[mushy] = (np.exp(-f * T[mushy]) - np.exp(-f * Tb2)) / denom

    dTheta = np.zeros_like(T)
    dTheta[mushy] = -f * np.exp(-f * T[mushy]) / denom

    return _finalize(Theta, dTheta, is_scalar)


_MODELS = {
    "lun": _lunardini,
    "l": _lunardini,
    "gal": _galushkin,
    "g": _galushkin,
    "nic": _nicolsky,
    "n": _nicolsky,
    "hin": _hinzman,
    "h": _hinzman,
}


def ftheta(model: str, **kwargs) -> dict:
    """
    Fluid/ice partition function dispatcher (translation of ftheta.m /
    ftheta_new.m).

    Parameters
    ----------
    model : str
        Which formulation to use: "lun"/"l", "gal"/"g", "nic"/"n", or
        "hin"/"h" (case-insensitive). See module docstring for the
        reference behind each.
    **kwargs :
        T : array-like or scalar, temperature in deg C (required).
        Model-specific parameters (all optional, defaulting exactly as in
        the original MATLAB):
            lun: Tf=0.0, w=0.5
            gal: Tf=0.0
            nic: Tf=-0.001, p=0.5   (requires 0.5 <= p <= 0.8, Tf < 0)
            hin: Tb=[-0.001, -2.0], p=10.0

    Returns
    -------
    dict
        {"Theta": <ndarray or float>, "dTheta": <ndarray or float>},
        with 0 <= Theta <= 1.
    """
    try:
        T = kwargs.pop("T")
    except KeyError:
        raise TypeError("ftheta: missing required keyword argument 'T'")

    fun = _MODELS.get(str(model).lower())
    if fun is None:
        raise ValueError(f"ftheta: unknown model '{model}'")

    return fun(T, **kwargs)


# ===========================================================================
# Fluid, ice, and rock/matrix thermophysical property functions
# ===========================================================================
#
# Translated from props/<site>/{cpfT,cpiT,cpmT,kfT,kiT,kmT,rcmT,rhofT,rhoiT}.m
# (props/arch and props/tmp were excluded per instructions, as were the
# props/*/propfit and props/aar/*.mat data files).
#
# Every one of these 14 site subdirectories (aar, bal, blz, const, fmk,
# full, lax, oku, olk, otn, sg3, str, syn, ull) defines its own .m file for
# each property, all sharing the same MATLAB function name (e.g. every
# subdir has a "cpmT.m"). Comparing the actual file contents (not just
# filenames) across all 14 subdirectories shows the collisions fall into
# two categories:
#
#   (a) purely mechanical differences -- row/column reshaping idioms
#       (`T=T(:)` vs `[n1,n2]=size(T); if n1==1, T=T'; end`), an unused
#       second output, trailing semicolons -- where the underlying formula
#       is identical. These collapse to a single Python function, since
#       numpy handles scalar/array shapes uniformly and this bookkeeping is
#       simply not needed.
#   (b) genuinely different formulas (different physical models or fitted
#       coefficients per site).
#
# After removing (a), the following distinct implementations remain. Each
# is named after the alphabetically-first site directory that uses it
# (kept as a stable, if somewhat arbitrary, identifying suffix), and its
# docstring lists every site that shares it. The SITE_PROPS dict at the
# end maps all 14 site codes to the correct function for each property, so
# call sites do not need to know which sites happen to share an
# implementation.
#
# Two source anomalies are worth flagging explicitly (also noted at the
# relevant function below):
#   - props/aar/cpmT.m has its Vosteen & Schellschmidt (2003) quadratic
#     formula entirely commented out; the only live statement is a
#     pass-through (`cpmT = cpm`). Reproduced as-is.
#   - props/sg3/cpmT.m is textually almost identical to a Kola-specific
#     rcmT formula (and even names its internal MATLAB function `rcmT`
#     while living in a file called `cpmT.m`) rather than implementing a
#     genuine heat-capacity-vs-temperature model. Reproduced as-is,
#     flagged for review.
#
# Calling convention (matches ftheta): every function below takes a single
# dict `model` (must contain "T", plus whatever site-specific parameters
# it needs) and returns a dict keyed by the corresponding MATLAB output
# variable name(s) -- e.g. cpfT_fehmn returns {"cpf": ...}, kmT_sg3
# returns {"kmT": ..., "dmT": ...} (its MATLAB form is [kmT,dmT]=kmT(...)).
# ---------------------------------------------------------------------

# --- fluid (pure water) properties ----------------------------------------


def cpfT_fehmn(model: dict) -> dict:
    """Pure water isobaric heat capacity [J/(kg*K)] as a function of
    temperature (deg C) and pressure (Pa), valid for P in 0.01-110 MPa and
    T in 15-350 deg C, extended below 0 C (down to -45 C) with the Speedy
    (1987) supercooled-water correlation.

    model: {"T": ..., "P": 0.1 (optional)}
    Returns {"cpf": ...}.

    Used by every site except "const": aar, bal, blz, fmk, full, lax, oku,
    olk, otn, sg3, str, syn, ull.

    Reference: Zylkovskij et al., Models and Methods Summary for the FEHMN
    Application, ECD 22, LA-UR-94-3787, Los Alamos National Laboratory,
    1994. (Low-temperature branch: Speedy, R. J., Thermodynamic properties
    of supercooled water at 1 atm, J. Phys. Chem., 1987, 91, 3354-3358.)
    Original MATLAB: vr, RWTH Aachen University, April 25, 2004.
    """
    T, is_scalar = _as_float_array(model["T"])
    P = np.broadcast_to(
        np.asarray(model.get("P", 0.1), dtype=float), T.shape
    ).copy()

    Pm = P / 1.0e6  # Pa -> MPa
    P2, P3 = Pm**2, Pm**3
    T2, T3 = T**2, T**3
    TP, T2P, TP2 = Pm * T, T2 * Pm, T * P2

    ac = [
        0.25623465e-3,
        0.10184405e-2,
        0.22554970e-4,
        0.34836663e-7,
        0.41769866e-2,
        -0.21244879e-4,
        0.25493516e-7,
        0.89557885e-4,
        0.10855046e-6,
        -0.21720560e-6,
        0.10000000e1,
        0.23513278e-1,
        0.48716386e-4,
        -0.19935046e-8,
        -0.50770309e-2,
        0.57780287e-5,
        0.90972916e-9,
        -0.58981537e-4,
        -0.12990752e-7,
        0.45872518e-8,
    ]

    a = (
        ac[0]
        + ac[1] * Pm
        + ac[2] * P2
        + ac[3] * P3
        + ac[4] * T
        + ac[5] * T2
        + ac[6] * T3
        + ac[7] * TP
        + ac[9] * T2P
        + ac[8] * TP2
    )
    b = (
        ac[10]
        + ac[11] * Pm
        + ac[12] * P2
        + ac[13] * P3
        + ac[14] * T
        + ac[15] * T2
        + ac[16] * T3
        + ac[17] * TP
        + ac[19] * T2P
        + ac[18] * TP2
    )
    da = (
        ac[4]
        + 2 * ac[5] * T
        + 3 * ac[6] * T2
        + ac[7] * Pm
        + 2 * ac[9] * TP
        + ac[8] * P2
    )
    db = (
        ac[14]
        + 2 * ac[15] * T
        + 3 * ac[16] * T2
        + ac[17] * Pm
        + 2 * ac[19] * TP
        + ac[18] * P2
    )

    cpf = (da / b - a * db / b**2) * 1.0e6

    bc = [14.2, 25.952, 128.281, -221.405, 196.894, -64.812]
    ic = T < 0.0
    Tclip = np.where(T < -45.0, -45.0, T)
    r = (Tclip[ic] + 273.15 - 227.15) / 227.15
    r2, r3, r4 = r**2, r**3, r**4
    cpf_ic = (
        bc[0] / np.sqrt(r)
        + bc[1]
        + bc[2] * r
        + bc[3] * r2
        + bc[4] * r3
        + bc[5] * r4
    )
    cpf_ic = cpf_ic * 0.99048992406520 * 1000.0 / 18.0
    cpf[ic] = cpf_ic

    return {"cpf": _result(cpf, is_scalar)}


def cpfT_const(model: dict) -> dict:
    """Pure water isobaric heat capacity, fixed at 4217.6 J/(kg*K)
    (site "const" dummy/placeholder model).

    model: {"T": ...}
    Returns {"cpf": ...}.
    """
    T, is_scalar = _as_float_array(model["T"])
    return {"cpf": _result(np.full_like(T, 4217.6), is_scalar)}


def rhofT_fehmn(model: dict) -> dict:
    """Pure water density [kg/m^3] as a function of temperature (deg C)
    and pressure (Pa), valid for P in 0.01-110 MPa and T in 15-350 deg C,
    extended below 0 C (down to -45 C) with the Speedy (1987)
    supercooled-water correlation.

    model: {"T": ..., "P": 0.1 (optional)}
    Returns {"rho": ...}.

    Used by every site except "const": aar, bal, blz, fmk, full, lax, oku,
    olk, otn, sg3, str, syn, ull.

    Reference: Zylkovskij et al., Models and Methods Summary for the FEHMN
    Application, ECD 22, LA-UR-94-3787, Los Alamos National Laboratory,
    1994. (Low-temperature branch: Speedy, R. J., 1987, as above.)
    Original MATLAB: vr, RWTH Aachen University, April 25, 2004.
    """
    T, is_scalar = _as_float_array(model["T"])
    P = np.broadcast_to(
        np.asarray(model.get("P", 0.1), dtype=float), T.shape
    ).copy()

    Pm = P / 1.0e6
    P2, P3 = Pm**2, Pm**3
    T2, T3 = T**2, T**3
    TP, T2P, TP2 = Pm * T, T2 * Pm, T * P2

    ac = [
        0.10000000e1,
        0.17472599e-1,
        -0.20443098e-4,
        -0.17442012e-6,
        0.49564109e-2,
        -0.40757664e-4,
        0.50676664e-7,
        0.50330978e-4,
        0.33914814e-6,
        -0.18383009e-6,
        0.10009476e-2,
        0.16812589e-4,
        -0.24582622e-7,
        -0.17014984e-9,
        0.48841156e-5,
        -0.32967985e-7,
        0.28619380e-10,
        0.53249055e-7,
        0.30456698e-9,
        -0.12221899e-9,
    ]

    a = (
        ac[0]
        + ac[1] * Pm
        + ac[2] * P2
        + ac[3] * P3
        + ac[4] * T
        + ac[5] * T2
        + ac[6] * T3
        + ac[7] * TP
        + ac[9] * T2P
        + ac[8] * TP2
    )
    b = (
        ac[10]
        + ac[11] * Pm
        + ac[12] * P2
        + ac[13] * P3
        + ac[14] * T
        + ac[15] * T2
        + ac[16] * T3
        + ac[17] * TP
        + ac[19] * T2P
        + ac[18] * TP2
    )
    rho = a / b

    bc = [
        0.999195706402050 * 901.5328593,
        -0.0011761652,
        0.0038442382,
        -0.0157270761,
        0.0744064614,
        -0.1406432653,
    ]
    ic = T < 0.0
    Tclip = np.where(T < -45.0, -45.0, T)
    r = (Tclip[ic] + 273.15 - 227.15) / 227.15
    r2, r3, r4 = r**2, r**3, r**4
    rho[ic] = bc[0] * np.exp(
        -227.15
        * (
            bc[2] * r
            + 0.5 * bc[3] * r2
            + (1.0 / 3.0) * bc[4] * r3
            + 0.25 * bc[5] * r4
            + 2 * bc[1] * np.sqrt(r)
        )
    )

    return {"rho": _result(rho, is_scalar)}


def rhofT_const(model: dict) -> dict:
    """Pure water density, fixed at 999.84 kg/m^3
    (site "const" dummy/placeholder model).

    model: {"T": ...}
    Returns {"rho": ...}.
    """
    T, is_scalar = _as_float_array(model["T"])
    return {"rho": _result(np.full_like(T, 999.84), is_scalar)}


def kfT_phillips(model: dict) -> dict:
    """Formation-water thermal conductivity [W/(m*K)] as a function of
    temperature (deg C) and NaCl salinity (mass fraction, g/g). Valid
    20-330 deg C, up to 4 molal NaCl.

    model: {"T": ..., "S": 0.0 (optional)}
    Returns {"kf": ..., "kfw": ...} (kfw is the freshwater-only value,
    matching the MATLAB [kf,kfw]=kfT(...) two-output form).

    Used by every site except "const": aar, bal, blz, fmk, full, lax, oku,
    olk, otn, sg3, str, syn, ull.

    Reference: Phillips, S. L.; Igbene, A.; Fair, J. A.; Ozbek, H. &
    Tavana, M., A technical databook for geothermal energy utilization,
    Lawrence Berkeley Laboratory Report 12810, 1981, 46 p.
    Fortran source: J. J. Adams, Alberta Geological Survey, May 2001.
    Original MATLAB: V. Rath, RWTH Aachen University, April 2004.
    """
    T, is_scalar = _as_float_array(model["T"])
    S = np.broadcast_to(np.asarray(model.get("S", 0.0), dtype=float), T.shape)

    Tr = (T + 273.15) / 273.15
    Tr2, Tr3, Tr4 = Tr**2, Tr**3, Tr**4
    kfw = -0.92247 + 2.8395 * Tr - 1.8007 * Tr2 + 0.52577 * Tr3 - 0.07344 * Tr4

    saline = S > 1.0e-7
    T2 = T**2
    C = S / (1.0 + S) * 1.0e2
    C2 = C**2
    kf_saline = kfw * (
        1.0
        - (2.3434e-3 - 7.924e-6 * T + 3.924e-8 * T2) * C
        + (1.06e-5 - 2.0e-8 * T - 1.2e-10 * T2) * C2
    )
    kf = np.where(saline, kf_saline, kfw)

    return {"kf": _result(kf, is_scalar), "kfw": _result(kfw, is_scalar)}


def kfT_const(model: dict) -> dict:
    """Formation-water thermal conductivity, fixed at 0.561 W/(m*K)
    (site "const" dummy/placeholder model).

    model: {"T": ...}
    Returns {"kf": ...}.
    """
    T, is_scalar = _as_float_array(model["T"])
    return {"kf": _result(np.full_like(T, 0.561), is_scalar)}


# --- ice properties ---------------------------------------------------


def cpiT_reg(model: dict) -> dict:
    """Ice isobaric heat capacity [J/(kg*K)], regression on published
    data, defined only for T < 0 C (near-zero placeholder above).

    model: {"T": ...}
    Returns {"cpi": ...}.

    Used by: aar, blz, oku, str, syn.
    """
    T, is_scalar = _as_float_array(model["T"])
    cpi = np.full_like(T, 1.0e-5)
    mask = T < 0.0
    cpi[mask] = 2110.0 + 7.7 * T[mask]
    return {"cpi": _result(cpi, is_scalar)}


def cpiT_fukosako(model: dict) -> dict:
    """Ice isobaric heat capacity [J/(kg*K)], valid for all T.

    model: {"T": ...}
    Returns {"cpi": ...}.

    Used by: bal, fmk, full, lax, olk, otn, sg3, ull.

    Reference: Fukusako, S., Thermophysical properties of ice, snow, and
    sea ice, International Journal of Thermophysics, 1990, 11, 353-372
    (p. 356).
    """
    T, is_scalar = _as_float_array(model["T"])
    Tk = T + 273.15
    cpi = 185.0 + 6.89 * Tk
    return {"cpi": _result(cpi, is_scalar)}


def cpiT_const(model: dict) -> dict:
    """Ice isobaric heat capacity, fixed at 2110 J/(kg*K)
    (site "const" dummy/placeholder model).

    model: {"T": ...}
    Returns {"cpi": ...}.
    """
    T, is_scalar = _as_float_array(model["T"])
    return {"cpi": _result(np.full_like(T, 2110.0), is_scalar)}


def rhoiT_reg(model: dict) -> dict:
    """Ice density [kg/m^3], regression on published data, defined only
    for T < 0 C (near-zero placeholder above).

    model: {"T": ...}
    Returns {"rhoi": ...}.

    Used by every site except "const": aar, bal, blz, fmk, full, lax, oku,
    olk, otn, sg3, str, syn, ull.
    """
    T, is_scalar = _as_float_array(model["T"])
    rhoi = np.full_like(T, 1.0e-5)
    mask = T < 0.0
    rhoi[mask] = 917.0 - 0.151 * T[mask]
    return {"rhoi": _result(rhoi, is_scalar)}


def rhoiT_const(model: dict) -> dict:
    """Ice density, fixed at 917 kg/m^3 (site "const" dummy/placeholder
    model).

    model: {"T": ...}
    Returns {"rhoi": ...}.
    """
    T, is_scalar = _as_float_array(model["T"])
    return {"rhoi": _result(np.full_like(T, 917.0), is_scalar)}


def kiT_reg(model: dict) -> dict:
    """Ice thermal conductivity [W/(m*K)], regression on published data,
    defined only for T < 0 C (near-zero placeholder above).

    model: {"T": ...}
    Returns {"ki": ...}.

    Used by every site except "const": aar, bal, blz, fmk, full, lax, oku,
    olk, otn, sg3, str, syn, ull.
    """
    T, is_scalar = _as_float_array(model["T"])
    ki = np.full_like(T, 1.0e-5)
    mask = T < 0.0
    ki[mask] = 2.164 - 0.0112 * T[mask]
    return {"ki": _result(ki, is_scalar)}


def kiT_const(model: dict) -> dict:
    """Ice thermal conductivity, fixed at 2.164 W/(m*K) (site "const"
    dummy/placeholder model).

    model: {"T": ...}
    Returns {"ki": ...}.
    """
    T, is_scalar = _as_float_array(model["T"])
    return {"ki": _result(np.full_like(T, 2.164), is_scalar)}


# --- rock/matrix heat capacity, cpmT ------------------------------------


def cpmT_aar(model: dict) -> dict:
    """Rock heat capacity as a function of temperature.

    NOTE: props/aar/cpmT.m has its Vosteen & Schellschmidt (2003)
    quadratic formula (see cpmT_blz) fully commented out in the MATLAB
    source; the only live statement is a pass-through, `cpmT = cpm`. That
    behaviour is reproduced verbatim here -- flag for review if the
    commented-out formula was actually meant to be active.

    model: {"cpm": ..., "T": ..., "P": None (unused), "T0": 25.0 (unused),
            "T1": 800.0 (unused)}
    Returns {"cpmT": ...}.

    Used by: aar.
    """
    cpm, is_scalar = _as_float_array(model["cpm"])
    return {"cpmT": _result(cpm, is_scalar)}


def cpmT_bal(model: dict) -> dict:
    """Rock heat capacity as a function of temperature, after
    Cermak & Rybach (fixed reference temperatures T0=20 C, T1=800 C).

    model: {"cpm": ..., "T": ...}
    Returns {"cpmT": ...}.

    Used by: bal, full, ull.

    Reference: Cermak, V. & Rybach, L., in Landolt-Boernstein, Vol. V/1a,
    Physical Properties of Rocks.
    Original MATLAB: vr, April 25, 2004.
    """
    T, is_scalar = _as_float_array(model["T"])
    cpm0 = np.broadcast_to(np.asarray(model["cpm"], dtype=float), T.shape)

    A, B, C = 754.0, 6.14e-4, 1.928e4
    T0, T1 = 20.0, 800.0
    TK, T0K, T1K = T + 273.15, T0 + 273.15, T1 + 273.15

    cp0 = A * (1 + B * T0K - C / T0K**2)
    f = cpm0 / cp0
    cp1 = A * (1 + B * T1K - C / T1K**2)
    cp = A * (1 + B * TK - C / (TK * TK))
    cp = np.where(T >= T1, cp1, cp)

    return {"cpmT": _result(f * cp, is_scalar)}


def cpmT_blz(model: dict) -> dict:
    """Rock heat capacity as a function of temperature, after
    Vosteen & Schellschmidt (2003), figure 4.

    model: {"cpm": ..., "T": ..., "T0": 25.0 (optional), "P": None (unused),
            "T1": 800.0 (unused)}
    Returns {"cpmT": ...}.

    Used by: blz, str.

    Reference: Vosteen, H.-D. & Schellschmidt, R., Influence of
    temperature on thermal conductivity, thermal capacity and thermal
    diffusivity for different types of rock, Physics and Chemistry of the
    Earth, 2003, 28, 499-509.
    Original MATLAB: vr, April 25, 2004.
    """
    T, is_scalar = _as_float_array(model["T"])
    cpm = np.broadcast_to(np.asarray(model["cpm"], dtype=float), T.shape)
    T0 = model.get("T0", 25.0)

    a, b = -0.0015, 1.0367
    Ts = T - T0
    cpmT = a * Ts * Ts + b * Ts + cpm

    return {"cpmT": _result(cpmT, is_scalar)}


def cpmT_const(model: dict) -> dict:
    """Rock heat capacity, pass-through / dummy: cpmT = cpm regardless of
    temperature (site "const" dummy/placeholder model).

    model: {"cpm": ..., "T": ...}
    Returns {"cpmT": ...}.
    """
    cpm, is_scalar = _as_float_array(model["cpm"])
    return {"cpmT": _result(cpm, is_scalar)}


def cpmT_fmk(model: dict) -> dict:
    """Rock heat capacity as a function of temperature, after Mottaghy
    (2005, 2007), fitted to Olkiluoto (OLK) data.

    model: {"cpm": ..., "T": ...}
    Returns {"cpmT": ...}.

    Used by: fmk, olk, otn.

    Original MATLAB: vr, Sep 13, 2014.
    """
    T, is_scalar = _as_float_array(model["T"])
    cpm0 = np.broadcast_to(np.asarray(model["cpm"], dtype=float), T.shape)

    A1, A2 = -0.00253, 1.46
    cpbas = 712.0
    f = cpm0 / cpbas
    cpm = 1.0e3 / (A1 * T + A2)

    return {"cpmT": _result(f * cpm, is_scalar)}


def cpmT_lax(model: dict) -> dict:
    """Rock heat capacity as a function of temperature, after Sundberg
    (2009) / Rath et al. (2018) -- linear increase with T.

    model: {"cpm": ..., "T": ...}
    Returns {"cpmT": ...}.

    Used by: lax.

    Original MATLAB: vr, Oct 2018.
    """
    T, is_scalar = _as_float_array(model["T"])
    cpm0 = np.broadcast_to(np.asarray(model["cpm"], dtype=float), T.shape)

    f = 0.25e-2
    cpmT = cpm0 + cpm0 * f * (T - 25.0)

    return {"cpmT": _result(cpmT, is_scalar)}


def cpmT_oku(model: dict) -> dict:
    """Rock heat capacity as a function of temperature, after
    Cermak & Rybach, with T0/T1 exposed as adjustable parameters
    (defaults match cpmT_bal).

    model: {"cpm": ..., "T": ..., "T0": 20.0 (optional), "T1": 800.0
            (optional)}
    Returns {"cpmT": ...}.

    Used by: oku.

    Reference: Cermak, V. & Rybach, L., in Landolt-Boernstein, Vol. V/1a,
    Physical Properties of Rocks.
    Original MATLAB: vr, April 25, 2004.
    """
    T, is_scalar = _as_float_array(model["T"])
    cp = np.broadcast_to(np.asarray(model["cpm"], dtype=float), T.shape)
    T0 = model.get("T0", 20.0)
    T1 = model.get("T1", 800.0)

    A, B, C = 754.0, 6.14e-4, 1.928e4
    TK, T0K, T1K = T + 273.15, T0 + 273.15, T1 + 273.15

    cp0 = A * (1 + B * T0K - C / T0K**2)
    f = cp / cp0
    cp1 = A * (1 + B * T1K - C / T1K**2)
    cpcalc = A * (1 + B * TK - C / (TK * TK))
    cpcalc = np.where(T >= T1, cp1, cpcalc)

    return {"cpmT": _result(f * cpcalc, is_scalar)}


def cpmT_sg3(model: dict) -> dict:
    """Rock heat capacity as a function of temperature (Kola SG3 data).

    NOTE: props/sg3/cpmT.m is textually almost identical to the
    Kola-specific rcmT formula (rcmT_sg3 below) rather than a genuine
    heat-capacity-vs-temperature model -- it even internally names its
    MATLAB function `rcmT` while living in a file called `cpmT.m`. This is
    reproduced verbatim (`cpm * 1e3 / (0.0044*T + 2.134)`); flag for
    review, this looks like a copy-paste artifact in the source rather
    than an intentional formula.

    model: {"cpm": ..., "T": ...}
    Returns {"cpmT": ...}.

    Used by: sg3.
    """
    T, is_scalar = _as_float_array(model["T"])
    cpm = np.broadcast_to(np.asarray(model["cpm"], dtype=float), T.shape)

    cpmT = cpm * 1.0e3 / (0.0044 * T + 2.134)

    return {"cpmT": _result(cpmT, is_scalar)}


def cpmT_syn(model: dict) -> dict:
    """Rock heat capacity, pass-through: cpmT = cpm regardless of
    temperature.

    model: {"cpm": ..., "T": ..., "P": None (unused), "T0": 25.0 (unused),
            "T1": 800.0 (unused)}
    Returns {"cpmT": ...}.

    Used by: syn.
    """
    cpm, is_scalar = _as_float_array(model["cpm"])
    return {"cpmT": _result(cpm, is_scalar)}


# --- rock/matrix thermal conductivity, kmT ------------------------------


def kmT_const(model: dict) -> dict:
    """Rock thermal conductivity, temperature-independent: kmT = k.

    model: {"k": ..., "T": None (unused, optional)}
    Returns {"kmT": ...}.

    Used by: aar, blz, str, syn, const (all four of these compute the
    same temperature-independent result; they only differ in MATLAB
    argument-list bookkeeping that has no Python equivalent).
    """
    k, is_scalar = _as_float_array(model["k"])
    return {"kmT": _result(k, is_scalar)}


def kmT_clauser(model: dict) -> dict:
    """Rock thermal conductivity as a function of temperature, after
    Clauser & Huenges (1995), AGU Reference Shelf, with default
    coefficients A=0.7, B=770, T0=20 C, T1=800 C.

    model: {"km0": ..., "T": ..., "A": 0.7 (optional), "B": 770.0
            (optional), "T0": 20.0 (optional), "T1": 800.0 (optional)}
    Returns {"kmT": ...}.

    Used by: bal, full, ull, oku (oku exposes an extra unused "Pcl"
    parameter in the MATLAB signature but is otherwise the same formula
    with the same defaults).

    Original MATLAB: v.r., Nov 2, 2002.
    """
    T, is_scalar = _as_float_array(model["T"])
    km0 = np.broadcast_to(np.asarray(model["km0"], dtype=float), T.shape)
    A = model.get("A", 0.7)
    B = model.get("B", 770.0)
    T0 = model.get("T0", 20.0)
    T1 = model.get("T1", 800.0)

    if A > 0:
        kbas = A + B / (350.0 + T0)
        klim = A + B / (350.0 + T1)
        kda = A + B / (350.0 + T)
        kda = np.where(T >= T1, klim, kda)
        f = km0 / kbas
        kmT = f * kda
    else:
        kmT = km0

    return {"kmT": _result(kmT, is_scalar)}


def kmT_olk(model: dict) -> dict:
    """Rock thermal conductivity as a function of temperature, same
    formula as kmT_clauser but with coefficients fitted to Olkiluoto
    (OLK) data (A=0.416, B=97.9, T0=25 C, T1=125 C).

    model: {"km0": ..., "T": ..., "A": 0.416 (optional), "B": 97.9
            (optional), "T0": 25.0 (optional), "T1": 125.0 (optional)}
    Returns {"kmT": ...}.

    Used by: fmk, olk, otn.

    Original MATLAB: vr, Sep 13, 2014.
    """
    defaults = {"A": 0.416, "B": 97.9, "T0": 25.0, "T1": 125.0}
    merged = {**defaults, **model}
    return kmT_clauser(merged)


def kmT_lax(model: dict) -> dict:
    """Rock thermal conductivity as a function of temperature, after
    Sundberg (2009) / Rath et al. (2018) -- linear decrease with T.

    model: {"km0": ..., "T": ...}
    Returns {"kmT": ...}.

    Used by: lax.

    Original MATLAB: vr, Oct 2018.
    """
    T, is_scalar = _as_float_array(model["T"])
    km0 = np.broadcast_to(np.asarray(model["km0"], dtype=float), T.shape)

    f = 0.03e-2 * km0
    kmT = km0 - f * (T - 25.0)

    return {"kmT": _result(kmT, is_scalar)}


def kmT_sg3(model: dict) -> dict:
    """Rock thermal conductivity as a function of temperature, for the
    Kola SG3 borehole.

    model: {"k": ..., "T": ..., "A": 0.0013 (optional), "B": 0.0029
            (optional)}
    Returns {"kmT": ..., "dmT": ...} (dmT = 0.45*kmT, matching the MATLAB
    two-output form [kmT,dmT]=kmT(...); computed unconditionally here
    since Python has no nargout).

    Used by: sg3.

    Reference: Vosteen, H.-D. et al., Physics and Chemistry of the Earth,
    2003, 28, 499-509; Mottaghy, D. et al., International Journal of
    Earth Sciences (Geologische Rundschau), 2008, 97, 435-442.
    Default coefficients A, B here are the "Kola" pair from the MATLAB
    comment (0.0013, 0.0029); the commented-out alternative in the source
    was the "sedimentary" pair (0.0034, 0.0039).
    Original MATLAB: vr, March 2013.
    """
    T, is_scalar = _as_float_array(model["T"])
    k = np.broadcast_to(np.asarray(model["k"], dtype=float), T.shape)
    A = model.get("A", 0.0013)
    B = model.get("B", 0.0029)

    Tlim = 800.0
    km0 = 0.53 * k + 0.5 * np.sqrt(1.13 * k**2 - 0.42 * k)

    denom = 0.99 + T * (A - B / km0)
    denom_lim = 0.99 + Tlim * (A - B / km0)
    kmT = np.where(T <= Tlim, km0 / denom, km0 / denom_lim)
    dmT = 0.45 * kmT

    return {"kmT": _result(kmT, is_scalar), "dmT": _result(dmT, is_scalar)}


# --- rock/matrix volumetric heat capacity, rcmT -------------------------


def rcmT_direct(model: dict, *, cpmT_func) -> dict:
    """Rock volumetric heat capacity: rcmT = rm * cpmT_func(cpm, T, P),
    i.e. density times a (site-specific) specific-heat-vs-temperature
    function.

    model: {"rm": ..., "cpm": ..., "T": ..., "P": None (optional)}
    `cpmT_func` must be the matching site's cpmT_* function (one of
    cpmT_aar, cpmT_blz, cpmT_syn for the sites that use this form).
    Returns {"rcmT": ...}.

    Used by: aar, blz, str, syn.
    """
    cpmT_val = cpmT_func(
        {"cpm": model["cpm"], "T": model["T"], "P": model.get("P")}
    )["cpmT"]
    return {"rcmT": model["rm"] * cpmT_val}


def rcmT_scaled(model: dict, *, cpmT_func) -> dict:
    """Rock volumetric heat capacity: rcmT = rcm * cpmT_func(cpm, T) / cpm,
    i.e. a reference volumetric heat capacity `rcm` rescaled by the
    (site-specific) specific-heat temperature dependence.

    model: {"rcm": ..., "cpm": ..., "T": ...}
    `cpmT_func` must be the matching site's cpmT_* function (one of
    cpmT_bal, cpmT_const, cpmT_fmk, cpmT_lax, cpmT_oku for the sites that
    use this form).
    Returns {"rcmT": ...}.

    Used by: bal, fmk, full, olk, ull, const, lax, oku, otn.
    """
    cpmT_val = cpmT_func({"cpm": model["cpm"], "T": model["T"]})["cpmT"]
    return {"rcmT": model["rcm"] * cpmT_val / model["cpm"]}


def rcmT_sg3(model: dict) -> dict:
    """Rock volumetric heat capacity for the Kola SG3 borehole, computed
    directly (does not call a separate cpmT function).

    model: {"rcm": ..., "cpm": ..., "T": ...}
    Returns {"rcmT": ...}.

    Used by: sg3.

    Reference: Kola SG3 data, per the MATLAB source comment.
    """
    T, is_scalar = _as_float_array(model["T"])
    rcm = np.broadcast_to(np.asarray(model["rcm"], dtype=float), T.shape)
    cpm = np.broadcast_to(np.asarray(model["cpm"], dtype=float), T.shape)

    rcm0 = rcm / cpm
    rcmT = rcm0 * 1.0 / (0.0044 * T + 2.134)

    return {"rcmT": _result(rcmT, is_scalar)}


# --- per-site registry ---------------------------------------------------
#
# Maps every site code to the correct implementation of each property.
# rcmT entries are bound (via functools.partial) to that site's own cpmT_*
# function, since the rcmT formula itself calls back into cpmT. Every
# entry takes and returns a dict, exactly like the standalone functions
# above.

import functools as _functools

_CPMT_BY_SITE = {
    "aar": cpmT_aar,
    "bal": cpmT_bal,
    "blz": cpmT_blz,
    "const": cpmT_const,
    "fmk": cpmT_fmk,
    "full": cpmT_bal,
    "lax": cpmT_lax,
    "oku": cpmT_oku,
    "olk": cpmT_fmk,
    "otn": cpmT_fmk,
    "sg3": cpmT_sg3,
    "str": cpmT_blz,
    "syn": cpmT_syn,
    "ull": cpmT_bal,
}

_RCMT_DIRECT_SITES = {"aar", "blz", "str", "syn"}
_KMT_CONST_SITES = {"aar", "blz", "str", "syn", "const"}
_KMT_CLAUSER_SITES = {"bal", "full", "ull", "oku"}
_KMT_OLK_SITES = {"fmk", "olk", "otn"}
_CPIT_REG_SITES = {"aar", "blz", "oku", "str", "syn"}

SITE_PROPS = {}
for _site in (
    "aar",
    "bal",
    "blz",
    "const",
    "fmk",
    "full",
    "lax",
    "oku",
    "olk",
    "otn",
    "sg3",
    "str",
    "syn",
    "ull",
):

    _cpmT_site = _CPMT_BY_SITE[_site]

    if _site in _RCMT_DIRECT_SITES:
        _rcmT_site = _functools.partial(rcmT_direct, cpmT_func=_cpmT_site)
    elif _site == "sg3":
        _rcmT_site = rcmT_sg3
    else:
        _rcmT_site = _functools.partial(rcmT_scaled, cpmT_func=_cpmT_site)

    if _site in _KMT_CONST_SITES:
        _kmT_site = kmT_const
    elif _site in _KMT_CLAUSER_SITES:
        _kmT_site = kmT_clauser
    elif _site in _KMT_OLK_SITES:
        _kmT_site = kmT_olk
    elif _site == "lax":
        _kmT_site = kmT_lax
    else:  # sg3
        _kmT_site = kmT_sg3

    SITE_PROPS[_site] = {
        "cpfT": cpfT_const if _site == "const" else cpfT_fehmn,
        "cpiT": (
            cpiT_const
            if _site == "const"
            else cpiT_reg if _site in _CPIT_REG_SITES else cpiT_fukosako
        ),
        "cpmT": _cpmT_site,
        "kfT": kfT_const if _site == "const" else kfT_phillips,
        "kiT": kiT_const if _site == "const" else kiT_reg,
        "kmT": _kmT_site,
        "rcmT": _rcmT_site,
        "rhofT": rhofT_const if _site == "const" else rhofT_fehmn,
        "rhoiT": rhoiT_const if _site == "const" else rhoiT_reg,
    }

del _site, _cpmT_site, _rcmT_site, _kmT_site
